[`flake8-quotes`] Deactivate `Q000` in tests focusing on `Q001`` Q002`
astral-sh/ruff pull request #10200
Opened 2024-03-02 17:46 UTC by robincaloudis

Not needed. Deactivation leads
to more granular tests.

https://github.com/astral-sh/ruff/pull/10199

## Summary

## Test Plan

2024-03-02 17:55 UTC, robincaloudis commented
@charliermarsh, do you mind to review this PR? Thank you.

2024-03-03 23:44 UTC, charliermarsh commented
There is arguably some value here because it ensures that these rules _aren't_ flagged in the docstring tests, right? I.e., that there are no false positives for `Q000`?

2024-03-06 16:41 UTC, MichaReiser requested changes
I'm reassigning this back to you, to reply to charlie's question.

2024-03-16 16:56 UTC, robincaloudis commented
I close this PR as I totally agree with the reviewers comments.

2024-03-16 16:56 UTC, closed without merging