[async-function-with-timeout] Disable check for asyncio before Python 3.11 (ASYNC109)
astral-sh/ruff pull request #13023
Opened 2024-08-21 07:28 UTC by vdwees

Some (occasionally tangential) discussion is found here: https://github.com/astral-sh/ruff/issues/12353

## Summary

Before, the diagnostic was raised for all supported versions of Python. However, `asyncio` only introduced the `asyncio.timeout` in python version 3.11.

Now, the diagnostic is not raised when using asyncio Python versions before 3.11

## Test Plan

It's a policy tweak leveraging well-tested library features. I don't see an obvious need for an additional test, but happy to receive guidance on how to add a test.

2024-08-22 07:59 UTC, MichaReiser commented
Thanks. This does make sense to me. However, it does mean that the rule now deviates from the upstream rule (I'm not sure if `flake8-async` has access to the target Python version). @AlexWaygood what's your take on this?

https://github.com/python-trio/flake8-async/blob/225f15a98db4bb8ce4600127fd0fe90bc5c9c04b/flake8_async/visitors/visitors.py#L43C7-L60


It would be great if we can add a test demonstrating that this is working as expected (flags asyncio but not anyio)

You can add the test here

https://github.com/astral-sh/ruff/blob/45f459bafd0663fd650dcd5750247f10a9f9126b/crates/ruff_linter/src/rules/flake8_async/mod.rs#L18-L39

and you can use the code below (you have to change the path to the python file)

```rust
    #[test]
    fn async109_python_310_or_odler() -> Result<()> {
        let diagnostics = test_path(
            Path::new("flake8_async").join("path_to_test_File"),
            &LinterSettings {
                target_version: PythonVersion::Py310,
                ..LinterSettings::for_rule(Rule::AsyncFunctionWithTimeout)
            },
        )?;
        assert_messages!(diagnostics);
        Ok(())
    }
```

2024-08-22 15:42 UTC, AlexWaygood commented
> Thanks. This does make sense to me. However, it does mean that the rule now deviates from the upstream rule (I'm not sure if `flake8-async` has access to the target Python version). @AlexWaygood what's your take on this?

Yeah, this change definitely makes sense to me! There are third-party libraries backporting `asyncio.timeout` to earlier Python versions, but I think that's irrelevant to the changes this PR is making. So this looks good, once it has a test added!

2024-08-22 16:08 UTC, MichaReiser requested changes
Perfect. Let's add a test and then merge this

2024-08-23 07:42 UTC, MichaReiser approved these changes

2024-08-23 08:02 UTC, merged