red-knot: Add not unary operator for integer literals
astral-sh/ruff pull request #13432
Opened 2024-09-21 00:34 UTC by haarisr

## Summary

Adds unary not operator (not) for integer literals.

Contributes to #12701
## Test Plan

Added new test basing of the test values in the `unary sub operator`. Small and large value for both positive and negative integers as well as for zero (which is the only True) test case

2024-09-21 04:11 UTC, AlexWaygood reviewed
Thanks!

2024-09-21 04:11 UTC, AlexWaygood commented on crates/red_knot_python_semantic/src/types/infer.rs
> +            },
you can simplify this slightly:

```suggestion
            (UnaryOp::Not, Type::IntLiteral(value)) => Type::BooleanLiteral(value == 0),
```

2024-09-21 04:26 UTC, carljm reviewed
Thank you!

I think for these other types what we should do is create a `Type::bool` method (corresponding to the `__bool__` magic method at runtime) that returns either BooleanLiteral (for those types whose Boolean value is statically known) or the `bool` builtin type. And then unary Not operator on most types will just call `bool` on the type and reverse it (if it's a BooleanLiteral.) Because we'll have other needs for the bool method outside unary Not.

2024-09-25 00:33 UTC, AlexWaygood requested changes
Following https://github.com/astral-sh/ruff/pull/13449 being merged, if you rebase this PR on `main` I think you can simplify this PR like so:

```diff
diff --git a/crates/red_knot_python_semantic/src/types.rs b/crates/red_knot_python_semantic/src/types.rs
index d388fa8b2..33a22a378 100644
--- a/crates/red_knot_python_semantic/src/types.rs
+++ b/crates/red_knot_python_semantic/src/types.rs
@@ -936,7 +936,6 @@ impl Truthiness {
         matches!(self, Truthiness::Ambiguous)
     }
 
-    #[allow(unused)]
     const fn negate(self) -> Self {
         match self {
             Self::AlwaysTrue => Self::AlwaysFalse,
@@ -945,7 +944,6 @@ impl Truthiness {
         }
     }
 
-    #[allow(unused)]
     fn into_type(self, db: &dyn Db) -> Type {
         match self {
             Self::AlwaysTrue => Type::BooleanLiteral(true),
diff --git a/crates/red_knot_python_semantic/src/types/infer.rs b/crates/red_knot_python_semantic/src/types/infer.rs
index 23ad71f3c..9b8362000 100644
--- a/crates/red_knot_python_semantic/src/types/infer.rs
+++ b/crates/red_knot_python_semantic/src/types/infer.rs
@@ -2210,11 +2210,7 @@ impl<'db> TypeInferenceBuilder<'db> {
 
         match (op, self.infer_expression(operand)) {
             (UnaryOp::USub, Type::IntLiteral(value)) => Type::IntLiteral(-value),
-            (UnaryOp::Not, Type::BooleanLiteral(value)) => Type::BooleanLiteral(!value),
-            (UnaryOp::Not, Type::IntLiteral(value)) => match value {
-                0 => Type::BooleanLiteral(true),
-                _ => Type::BooleanLiteral(false),
-            },
+            (UnaryOp::Not, ty) => ty.bool(self.db).negate().into_type(self.db),
             _ => Type::Unknown, // TODO other unary op types
         }
     }
```

but we'll also want to add a fair few tests, because we'll now be implementing `not` for _all_ variants of `Type` rather than just one ;)

2024-09-25 04:40 UTC, haarisr reviewed
Did most of the types that I could.

Would like help on tests for `Type::Any | Type::Never | Type::Unknown | Type::Unbound`

2024-09-25 04:40 UTC, haarisr commented on crates/red_knot_python_semantic/src/types/infer.rs
> +        assert_public_ty(&db, "src/a.py", "b", "Literal[False]");
The test for `b` fails. Not sure why the returned type is `bool`. Any help here would be appreciated

2024-09-25 19:01 UTC, carljm reviewed
Looks good to me! Just needs the failing test assertion commented out for now, with TODO comment.

2024-09-25 20:43 UTC, carljm approved these changes

2024-09-25 20:44 UTC, merged