Expose internal types as public access
astral-sh/ruff pull request #13509
Opened 2024-09-25 09:21 UTC by zao111222333

## Summary

Thanks for providing such a powerful project! 
I try to use `ruff_python_parser` as tokenizer for my toy python REPL project, https://github.com/zao111222333/pyapp.
Everything is so great besides some necessary types/APIs is internal rightnow. And I request expose them. Thanks again!

btw, here is a small example for the python REPL, `ruff_python_parser` is used to highlight & incomplete detect.
![](https://raw.githubusercontent.com/zao111222333/pyapp/refs/heads/main/demo.svg)

## Test Plan

I believe those changes will not change the functionality, so no test plan :)

2024-09-25 10:42 UTC, MichaReiser requested changes
Hi. Nice that you're finding our parser useful. 

I'm open to making `LexicalErrorType` public but I rather not make the other changes.

2024-09-25 10:42 UTC, MichaReiser commented on crates/ruff_python_parser/src/lib.rs
> +pub use ruff_python_ast::{Expr, Mod, ModExpression, ModModule, PySourceType, Suite};
This should not be necessary. You can use the `ruff_python_ast` directly

2024-09-25 10:42 UTC, MichaReiser commented on crates/ruff_python_parser/src/lib.rs
> +#[derive(Debug, PartialEq, Clone, Default)]
Can you explain me the use case for adding a `Default` implementation for `Parsed` and `Tokens` ?

2024-09-25 10:42 UTC, MichaReiser commented on crates/ruff_python_ast/src/nodes.rs
> +#[derive(Clone, Debug, PartialEq, Default)]
Same here, it's unclear what the use case for `Default` is.

2024-09-25 19:27 UTC, zao111222333 commented
> Hi. Nice that you're finding our parser useful.
> 
> I'm open to making `LexicalErrorType` public but I rather not make the other changes.

Hi, thank you for the suggestions. 
I need to store the tokens (`Tokens`/`Vec<Token>`) and errors (`Vec<ParseError>`), the initalization is required at beginning, so I add `Defualt` impl for some internal structs in previous commit.
And now I change to access the `Vec<Token>` and `Vec<ParseError>`, so that I can store the `Vec` and init with `Vec::new()`.
Here is my update

2024-09-26 06:37 UTC, MichaReiser commented
> Hi, thank you for the suggestions.
> I need to store the tokens (Tokens/Vec<Token>) and errors (Vec<ParseError>), the initalization is required at beginning, so I add Defualt impl for some internal structs in previous commit.
> And now I change to access the Vec<Token> and Vec<ParseError>, so that I can store the Vec and init with Vec::new().
> Here is my update

Do you have a link to some code that I can look at? I would prefer to keep those types as private as possible.

2024-09-26 07:22 UTC, zao111222333 commented
> Do you have a link to some code that I can look at? I would prefer to keep those types as private as possible.

Sure, pls have a look at:
+ Store the `tokens` & `errors`, update them once the input code is changed
https://github.com/zao111222333/pyapp/blob/main/src/app.rs#L98-L99
https://github.com/zao111222333/pyapp/blob/main/src/app.rs#L163-L172
+ Incomplete detect
https://github.com/zao111222333/pyapp/blob/main/src/app.rs#L112-L151
+ Static code highlight
https://github.com/zao111222333/pyapp/blob/main/src/app.rs#L206-L364

2024-09-26 07:33 UTC, zao111222333 commented
btw, I have modified my commit, which I believe is not as rude as before. Pls see
https://github.com/astral-sh/ruff/pull/13509/commits/11ab0dbbdb1d901244e6ae941a35eaf86cd2a752

2024-09-26 08:34 UTC, MichaReiser commented
Thanks for sharing your code. I don't think we need most of these changes.

I suggest that you:

* Change `MyHelper` to store a `Parsed` 
* You can call `parse_unchecked_source("")` to get a "default" parsed. This is slightly more expensive than calling `Parsed::default` (which doesn't exist) but shouldn't be that expensive because the lexer and parser will exit immediately (it's an empty string)

We then only need to make `LexicalErrorType` public which I think is a good change.

2024-09-26 08:38 UTC, MichaReiser commented
And the repl looks very impressive!

2024-09-26 15:30 UTC, MichaReiser approved these changes

2024-09-26 15:32 UTC, zao111222333 commented
Thank you for your suggestion! I also believe that is a good way to get default parsed. And here is the changes as your suggestion.
Thanks again :)

2024-09-26 15:34 UTC, MichaReiser commented
Thank you. This looks good

2024-09-26 15:34 UTC, merged