[DOCS] Add CrowdCent `numerblox` to Ruff users.
astral-sh/ruff pull request #13569
Opened 2024-09-30 13:49 UTC by CarloLepelaars

Hi, our open source project [NumerBlox](https://github.com/crowdcent/numerblox) started migrating to `uv` and `ruff`. Would appreciate the project being included in the list of Ruff users.

## Summary

Add [NumerBlox](https://github.com/crowdcent/numerblox) to Ruff users in README.md

2024-10-07 12:52 UTC, MichaReiser requested changes
Could you take a look at the formatting (the pre-commit test is failing)

2024-10-07 13:10 UTC, MichaReiser commented
Adding it to `types.toml should do the job

2024-10-07 13:28 UTC, CarloLepelaars commented
I've added `NumerBlox` to `_typos.toml`, but unfortunately the pre-commit still fails. Is there something I'm missing?

2024-10-07 15:17 UTC, calumy commented
> I've added `NumerBlox` to `_typos.toml`, but unfortunately the pre-commit still fails. Is there something I'm missing?
Could you try just `Numer` rather than `NumerBlox` as this is the bit that typos appears to be trying to correct.

2024-10-07 22:24 UTC, CarloLepelaars commented
> Could you try just `Numer` rather than `NumerBlox` as this is the bit that typos appears to be trying to correct.

Thank you for the suggestion @calumy! All CI is passing now!

2024-10-28 14:53 UTC, merged

2024-10-28 14:54 UTC, charliermarsh commented
Thank you for the PR @CarloLepelaars. Just as a heads up, I may remove this in the future as I'd like to redo the list to focus it on "highly notable" projects (either significant open source usage or from well-known enterprises).

2024-10-28 15:27 UTC, CarloLepelaars commented
That's ok @charliermarsh. Thank you for including us in the list in the meantime!