[`perflint`] - Fix `manual-list-comprehension` for async generators (`PERF401`)
astral-sh/ruff pull request #14551
Opened 2024-11-23 02:52 UTC by diceroll123

## Summary

Fixes a current bug in PERF401's preview autofix, where it tries to make an async generator within a list.extend, without wrapping the generator in a list, which does not implement `__iter__` which makes it an error.

## Test Plan

`cargo test`

2024-11-23 07:10 UTC, diceroll123 commented
[Found a weird issue with comments](https://play.ruff.rs/9d4b2182-b10b-4c1f-a584-4b40999e90c0), this was already present in the autofix in `0.8.0`, but I decided to fix it and put it in here too.

2024-11-23 16:41 UTC, Skylion007 commented
@w0nder1ng Another edge case. May want to merge this PR with #14369

2024-11-23 22:53 UTC, diceroll123 commented
Hm, yeah, my implementation does not do well with this one:

```py
def f():
    # make sure that `tmp` is not deleted
    tmp = 1; result = [] # commment should be protected
    for i in range(10):
        result.append(i + 1) # PERF401
```

2024-12-12 08:12 UTC, MichaReiser commented
@diceroll123 #14369 is now merged. Would you mind rebasing your PR?

2024-12-12 08:13 UTC, MichaReiser requested changes
Needs rebase

2025-01-15 10:18 UTC, closed without merging

2025-01-15 10:18 UTC, diceroll123 commented
Woop, destroyed the commit here by accident, but after fixing it locally and coming back from rebase hell, it turns out all of the issues my PR solved were solved by 14369, so I'll close this. Thanks all! 😄

2025-01-15 10:50 UTC, MichaReiser commented
Thank you!