Only run pyproject.toml lint rules when enabled
astral-sh/ruff pull request #5578
Opened 2023-07-07 03:06 UTC by charliermarsh

## Summary

I was testing some changes on Airflow, and I realized that we _always_ run the `pyproject.toml` validation rules, even if they're not enabled. This PR gates them behind the appropriate enablement flags.

## Test Plan

- Ran: `cargo run -p ruff_cli -- check ../airflow -n`. Verified that no RUF200 violations were raised.
- Run: `cargo run -p ruff_cli -- check ../airflow -n --select RUF200`. Verified that two RUF200 violations were raised.

2023-07-07 05:07 UTC, MichaReiser approved these changes

2023-07-07 07:52 UTC, konstin requested changes
I'd implement this differently: Only call `lint_pyproject_toml` if `InvalidPyprojectToml` is enabled, but then raise the io error unconditionally; The io error isn't a real lint but a way to communicate an error (we couldn't read the file, check permissions/filesystem/etc.) using our usual diagnostics system

2023-07-07 13:57 UTC, charliermarsh commented
@konstin - What about outputting an error to the log, but keeping the conditional? That's what we do for Python files:

```rust
error!(
    "{}{}{} {message}",
    "Failed to lint ".bold(),
    fs::relativize_path(path).bold(),
    ":".bold()
);
let settings = resolver.resolve(path, pyproject_config);
if settings.rules.enabled(Rule::IOError) {
    let file =
        SourceFileBuilder::new(path.to_string_lossy().as_ref(), "").finish();

    Diagnostics::new(
        vec![Message::from_diagnostic(
            Diagnostic::new(IOError { message }, TextRange::default()),
            file,
            TextSize::default(),
        )],
        ImportMap::default(),
    )
} else {
    Diagnostics::default()
}
```

2023-07-08 13:33 UTC, konstin approved these changes
I made io error handling consistent in #5611, which build on top of this PR. I'm not happy with it being possible to disable io errors, but this is unrelated to the pyproject.toml rule.

2023-07-08 15:05 UTC, merged