Check .git in formatter progress checkouts for build
astral-sh/ruff pull request #6387
Opened 2023-08-07 11:11 UTC by konstin

From the formatter progress CI logs:
```
2023-08-07T03:49:02.5178602Z + mkdir -p /home/runner/work/ruff/ruff/target/progress_projects
2023-08-07T03:49:02.5193474Z + '[' '!' -d /home/runner/work/ruff/ruff/target/progress_projects/build ']'
2023-08-07T03:49:02.5194228Z + '[' '!' -d /home/runner/work/ruff/ruff/target/progress_projects/django ']'
2023-08-07T03:49:02.5194966Z + git clone --filter=tree:0 https://github.com/django/django /home/runner/work/ruff/ruff/target/progress_projects/django
2023-08-07T03:49:02.5209260Z Cloning into '/home/runner/work/ruff/ruff/target/progress_projects/django'...
```
```
2023-08-07T03:51:17.4726088Z [2m2023-08-07T03:51:17.472404Z[0m [31mERROR[0m Failed /home/runner/work/ruff/ruff/target/progress_projects/build: no python files in ["/home/runner/work/ruff/ruff/target/progress_projects/build"]
```

Seems that build exists but is an empty cached folder. These changes should fix this by a) checking for `.git` instead of just the folder existing b) running the commit checkout unconditionally. The latter is also important if we ever want to update the SHAs.

2023-08-07 11:52 UTC, konstin commented
The CI failure is unrelated, this fixes the problem with build it was intended to fix

2023-08-07 12:06 UTC, MichaReiser commented
Do we know what's caching the folder in the first place? Because I didn't see any caching configuration related to it.

2023-08-07 12:26 UTC, konstin commented
i don't know what caused this intially

2023-08-08 09:55 UTC, MichaReiser requested changes
Okay I think I know what the problem is. If I understand it correctly, the script clones into the `target` directory. However, the target directory gets cached by [`rust-cache`. ](https://github.com/Swatinem/rust-cache).

I didn't see an option to exclude a specific directory. One option could be to add a CLI command that removes the checked-out project directory to avoid including them in the rust cache.

2023-08-08 10:14 UTC, konstin commented
I think it does clean "Anything that is not a dependency.", it's just that `build` looks like something that needs to be cached (https://github.com/Swatinem/rust-cache/blob/b919e1427f59422679cf2ed5fc6ddc010f753026/src/cleanup.ts#L37)

2023-08-08 15:46 UTC, merged